<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>ru.sprbut</groupId>
        <artifactId>sprbut-course</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>

    <artifactId>09-reflection-vs-apt</artifactId>
    <name>SprBut :: 09 :: Reflection vs APT vs байткод</name>

    <dependencies>
        <!-- Третий механизм со слайда 75: генерация байткода в runtime -->
        <dependency>
            <groupId>net.bytebuddy</groupId>
            <artifactId>byte-buddy</artifactId>
        </dependency>
    </dependencies>
</project>
