/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 Учебные репозитории
 * SPDX-License-Identifier: MIT
 */
// @checkstyle MultiLineCommentCheck disable
// проверки процессора построены на текстовых блоках с исходным кодом:
// внутри них лежит Java-текст примера, и переносить его по правилам
// оформления нельзя — тогда проверяется уже не тот исходник
// @checkstyle BracketsStructureCheck disable
// @checkstyle CascadeIndentationCheck disable
package ru.sprbut.m07.bytecode;

import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import org.hamcrest.MatcherAssert;
import org.hamcrest.Matchers;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import ru.sprbut.m07.CompilationHarness;
import ru.sprbut.m07.api.Meta;

/**
 * Генерация байткода: Filer пишет класс, javac его не компилирует.
 * @since 1.0
 */
@DisplayName("Генерация байткода: Filer пишет класс, javac его не компилирует")
final class BytecodeProcessorTest {

    /**
     * Помеченный класс с двумя методами.
     */
    private static final CompilationHarness.Source SERVICE = new CompilationHarness.Source(
            "demo.UserService", """
                    package demo;

                    import ru.sprbut.m07.api.Instrumented;

                    @Instrumented
                    public class UserService {

                        public String find() { return "пользователь"; }

                        public void save(String name) { }
                    }
                    """);

    /**
     * Обычный код, который ссылается на сгенерированный паспорт по имени.
     */
    private static final CompilationHarness.Source CLIENT = new CompilationHarness.Source(
            "demo.Client", """
                    package demo;

                    public class Client {

                        public String origin() { return new UserServiceMeta().origin(); }
                    }
                    """);

    /**
     * Рабочий каталог.
     */
    @TempDir
    private Path dir;

    @Test
    @DisplayName("Паспорт кладётся готовым классом рядом со скомпилированными")
    void writesClassFileNextToCompiledCode() {
        MatcherAssert.assertThat(
            "bytecode written through Filer cannot land in the output directory",
            Files.exists(
                this.compile(List.of(BytecodeProcessorTest.SERVICE))
                    .classesDir()
                    .resolve("demo/UserServiceMeta.class")
            ),
            Matchers.is(true)
        );
    }

    @Test
    @DisplayName("Сгенерированный класс знает, для кого он собран")
    void namesItsOrigin() throws ReflectiveOperationException {
        MatcherAssert.assertThat(
            "generated class cannot remember the type it was built for",
            this.meta(BytecodeProcessorTest.SERVICE).origin(),
            Matchers.equalTo("demo.UserService")
        );
    }

    @Test
    @DisplayName("Число методов посчитано компилятором и запечено в константу")
    void countsMethodsAtCompileTime() throws ReflectiveOperationException {
        MatcherAssert.assertThat(
            "compiler cannot bake the method count into the generated bytecode",
            this.meta(BytecodeProcessorTest.SERVICE).methods(),
            Matchers.equalTo(2)
        );
    }

    @Test
    @DisplayName("Исходников этот процессор не оставляет вовсе")
    void leavesNoSources() {
        MatcherAssert.assertThat(
            "processor that writes bytecode cannot leave sources behind",
            this.compile(List.of(BytecodeProcessorTest.SERVICE)).generatedSources(),
            Matchers.anEmptyMap()
        );
    }

    @Test
    @DisplayName("Обычный код ссылается на сгенерированный класс по имени")
    void staysVisibleToSources() throws ReflectiveOperationException {
        MatcherAssert.assertThat(
            "javac cannot resolve a type that came from the Filer as ready bytecode",
            BytecodeProcessorTest.origin(
                this.compile(
                    List.of(BytecodeProcessorTest.SERVICE, BytecodeProcessorTest.CLIENT)
                ).load("demo.Client")
            ),
            Matchers.equalTo("demo.UserService")
        );
    }

    private static String origin(final Class<?> client) throws ReflectiveOperationException {
        return client.getMethod("origin")
            .invoke(client.getDeclaredConstructor().newInstance())
            .toString();
    }

    private CompilationHarness.Result compile(final List<CompilationHarness.Source> sources) {
        return CompilationHarness.compile(this.dir, sources, new BytecodeProcessor());
    }

    private Meta meta(final CompilationHarness.Source source) throws ReflectiveOperationException {
        return (Meta) this.compile(List.of(source))
            .load(String.format("%sMeta", source.qualifiedName()))
            .getDeclaredConstructor()
            .newInstance();
    }
}
